version: "3.7"
services:
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==sparkmaster"
  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==sparkmaster"
#  spark-worker-2:
#    image: bde2020/spark-worker:2.4.0-hadoop2.7
#    container_name: spark-worker-2
#    depends_on:
#      - spark-master
#    environment:
#      - "SPARK_MASTER=spark://spark-master:7077"
#      - "constraint:node==sparkmaster"
#  spark-worker-3:
#    image: bde2020/spark-worker:2.4.0-hadoop2.7
#    container_name: spark-worker-3
#    depends_on:
#      - spark-master
#    environment:
#      - "SPARK_MASTER=spark://spark-master:7077"
#      - "constraint:node==sparkmaster"
  spark-client:
    image: spark-client
    container_name: spark-client
    ports:
      - "4040:4040"
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==sparkmaster"
    volumes:
      - ${yelp_input_file}:/tmp/yelp.tar
